version: '3'
services:
  ipcontainer:
    build: .
    volumes:
      - .:.
    env_file:
      - .env
    environment:
      - MYSQL_KEY= ${MYSQL_KEY}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 5001:5000
    command: python3 application.py